apiVersion: v1
kind: Service
metadata:
  name: takehome-service
spec:
  selector:
    app: takehome
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takehome
spec:
  selector:
    matchLabels:
      app: takehome
  replicas: 1
  template:
    metadata:
      labels:
        app: takehome
    spec:
      containers:
      - name: takehome
        image: takehome:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000